### PR TITLE
the current combination of maven plugin versions are causing ClassNotFoundException with maven 3

### PR DESCRIPTION
**Pull request by fabiokung**
java.lang.ClassNotFoundException: org.apache.maven.toolchain.ToolchainManager

### CODE REVIEW

**Comment by rodolfoliviero** [comment]
Removing versions for plugins maven 3 warning that it might not build in the future. 
and change the versions for older versions can solve the problem?
How can I reproduce the problem?

**Comment by fabiokung** [comment]
I am sorry, my mistake. Later I found that the problem actually happens with older version of maven (such as 2.0.8), and not maven 3. 

I can see two ways to reproduce: 1) follow the steps in my last blog post to deploy VRaptor apps to Heroku. You will be able to see the problem when running `lein deps`, which uses an old version of an embedded maven. And 2) running mvn tasks through a fairly old ant (1.6 should do) and the maven-ant-tasks. Particularly, the artifact:mvn task, when not pointed to a MAVEN_HOME dir, will download and use ab embedded mvn. 

That way should allow to us to try older versions of plugins that are compatible.

**Comment by rodolfoliviero** [comment]
maven-compiler-plugin is the guilty any version after 2.0.2 breaking on maven 2.0.10 or older.
Could you update this pull request?

**Comment by rodolfoliviero** [comment]
now a days heroku has native support for java. Thanks

Closing...

**Pull request closed without merging**
